Set to use no system classloader in test plugins.
This is caused by certain java / OS / test combinations recently started
failing to load the tests when running `failsafe` or `surefire` test
plugins.

```
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter
Caused by: java.lang.ClassNotFoundException: org.apache.maven.surefire.booter.ForkedBooter
```

Setting the noSystemClassLoader flag to false fixes this.